extends:
  - eslint:recommended
  - prettier # always comes last!

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures: 
    jsx: True

env:
  es6: true
  browser: true
  node: true
